### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by sagedemage** [phillipebarreto1/IS373LaravelDockerTest#10]
# Unit Tests 
Write unit tests for ensuring the quality of the web application.

## Tasks
- [x] Unit test for creating the movie entry (CREATE)
- [x] Unit test for getting the movie entry (READ)
- [x] Unit test for updating the movie entry (UPDATE)
- [x] Unit test for deleting the movie entry (DELETE)

## Resources
- [Laravel - Testing: Getting Started](https://laravel.com/docs/10.x/testing)
- [How to Get Started with Unit Testing in Laravel](https://betterstack.com/community/guides/testing/laravel-unit-testing/)
- [Use Laravel Unit Testing to Avoid Project-Wrecking Mistakes](https://www.cloudways.com/blog/laravel-unit-testing/)

**Comment by sagedemage** [comment]
```
git fetch origin
git checkout 10-unit-tests
```
