### ISSUE TITLE
Authentication Middleware

### ISSUE THREAD

**Issue by sagedemage** [phillipebarreto1/IS373LaravelDockerTest#32]
# Authentication Middleware
Previously, I did authentication the tedious way and that functionality does not comply with DRY (Don't Repeat Yourself). Laravel has the feature to use a middleware. So essentially I have to create an authentication middleware in order to guard the routes that require authentication. 

## Tasks
- [x] Create Authentication middleware and utilize for each route that needs it
  - Do not use authentication middleware for main movie route since it needs to get movie data. 

### Extras
- [x] Avoid repetition and only utilize JWT encoder and decoder methods of the MyJWT class.
- [x] Fix logic for user login action
- [x] Fix login for register action
- [x] Write unit tests for authentication

## Resources
- [Laravel - Middleware](https://laravel.com/docs/10.x/middleware#defining-middleware)

**Comment by sagedemage** [comment]
```
git fetch origin
git checkout 32-authentication-middleware
```
